//! Structural 3-way merge for poetry.lock.
//!
//! Same shape as cargo-lock-merge: treats the lockfile as a set of
//! `[[package]]` entries keyed by exact `name@version`, 3-way merges the
//! sets, then collapses same-name duplicates introduced by the merge itself
//! (both branches bumped the same dependency) by keeping the higher version.
//! Poetry only locks multiple versions of one package with environment
//! markers, so duplicates that already coexist on a single side are kept.
//! The `[metadata]` content-hash cannot be recomputed offline: when both
//! sides changed it we take theirs and tell the user to refresh it.
//!
//! Invoked by the gitwasm host as: poetry-lock-merge <base> <ours> <theirs> <result> [path]

use std::collections::BTreeMap;
use std::process::exit;
use toml::{Table, Value};

#[cfg_attr(test, derive(Clone))]
struct Lock {
    /// `[[package]]` entries keyed by `name@version`; `package.files` and
    /// everything else in an entry travel wholesale with it.
    packages: BTreeMap<String, Table>,
    metadata: Table,
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() < 5 {
        eprintln!("usage: poetry-lock-merge <base> <ours> <theirs> <result> [path]");
        exit(2);
    }
    let base = read_lock(&args[1]);
    let ours = read_lock(&args[2]);
    let theirs = read_lock(&args[3]);

    let (doc, notes) = merge3(&base, &ours, &theirs);
    for note in notes {
        eprintln!("poetry-lock-merge: {note}");
    }
    std::fs::write(&args[4], render(doc)).expect("write result");
    eprintln!("poetry-lock-merge: clean structural merge");
}

/// Render with poetry's header and section order (package, then metadata).
/// The two tables are serialized as separate documents because the toml
/// serializer emits map keys alphabetically, which would put `[metadata]`
/// first.
fn render(mut doc: Table) -> String {
    let mut text = String::from(
        "# This file is automatically @generated by Poetry and should not be changed by hand.\n",
    );
    for key in ["package", "metadata"] {
        if let Some(value) = doc.remove(key) {
            let mut section = Table::new();
            section.insert(key.into(), value);
            text.push('\n');
            text.push_str(&toml::to_string(&section).expect("serialize merged poetry.lock"));
        }
    }
    text
}

fn read_lock(path: &str) -> Lock {
    let text = std::fs::read_to_string(path).unwrap_or_default();
    match parse(&text) {
        Ok(lock) => lock,
        Err(err) => {
            eprintln!("poetry-lock-merge: {path} is not valid TOML ({err}) — refusing");
            exit(1);
        }
    }
}

fn parse(text: &str) -> Result<Lock, toml::de::Error> {
    let mut lock = Lock {
        packages: BTreeMap::new(),
        metadata: Table::new(),
    };
    if text.trim().is_empty() {
        return Ok(lock); // absent side (e.g. empty base when there is no common ancestor)
    }
    let doc: Table = text.parse()?;
    if let Some(Value::Array(packages)) = doc.get("package") {
        for pkg in packages {
            if let Value::Table(table) = pkg {
                let name = table.get("name").and_then(Value::as_str).unwrap_or("");
                let version = table.get("version").and_then(Value::as_str).unwrap_or("");
                lock.packages
                    .insert(format!("{name}@{version}"), table.clone());
            }
        }
    }
    if let Some(Value::Table(metadata)) = doc.get("metadata") {
        lock.metadata = metadata.clone();
    }
    Ok(lock)
}

/// Merge the package sets and the metadata table. Never hard-conflicts:
/// every both-changed case has a defensible resolution poetry can validate
/// or regenerate on the next `poetry lock`.
fn merge3(base: &Lock, ours: &Lock, theirs: &Lock) -> (Table, Vec<String>) {
    let mut notes = Vec::new();

    let mut keys: Vec<&String> = base
        .packages
        .keys()
        .chain(ours.packages.keys())
        .chain(theirs.packages.keys())
        .collect();
    keys.sort();
    keys.dedup();
    let mut merged: BTreeMap<String, Table> = BTreeMap::new();
    for key in keys {
        let (b, o, t) = (
            base.packages.get(key),
            ours.packages.get(key),
            theirs.packages.get(key),
        );
        let winner = if o == t {
            o
        } else if o == b {
            t
        } else if t == b {
            o
        } else if o.is_none() || t.is_none() {
            // Deleted on one side, metadata edited on the other: the edit
            // proves the entry is still wanted, so it wins.
            notes.push(format!(
                "{key}: deleted vs modified, keeping the modified entry"
            ));
            o.or(t)
        } else {
            // Same name@version, differing metadata on both sides. Take
            // theirs and say so — poetry validates hashes on next install.
            notes.push(format!(
                "{key}: metadata differs on both sides, taking theirs"
            ));
            t
        };
        if let Some(entry) = winner {
            merged.insert(key.clone(), entry.clone());
        }
    }

    // Collapse same-name duplicates the merge itself introduced (concurrent
    // bumps): keep the higher version. Names that were already multi-version
    // on some side carry environment markers and are legitimate — keep all.
    let mut by_name: BTreeMap<String, Vec<(Vec<u64>, String, Table)>> = BTreeMap::new();
    for (key, entry) in merged {
        let (name, version) = key.rsplit_once('@').unwrap_or((key.as_str(), ""));
        by_name.entry(name.to_string()).or_default().push((
            parse_version(version),
            version.to_string(),
            entry,
        ));
    }
    let mut packages: Vec<(String, Vec<u64>, String, Table)> = Vec::new();
    for (name, mut versions) in by_name {
        versions.sort_by(|a, b| (&a.0, &a.1).cmp(&(&b.0, &b.1)));
        if versions.len() > 1 && !multi_version_in_inputs(&name, [base, ours, theirs]) {
            let (_, kept, _) = versions.last().unwrap();
            let dropped: Vec<&str> = versions[..versions.len() - 1]
                .iter()
                .map(|(_, v, _)| v.as_str())
                .collect();
            notes.push(format!(
                "{name}: both branches bumped, keeping {kept} over {}",
                dropped.join(", ")
            ));
            versions.drain(..versions.len() - 1);
        }
        for (parsed, version, entry) in versions {
            packages.push((name.clone(), parsed, version, entry));
        }
    }
    packages.sort_by(|a, b| (&a.0, &a.1, &a.2).cmp(&(&b.0, &b.1, &b.2)));

    let metadata = merge_metadata(base, ours, theirs, &mut notes);

    let mut doc = Table::new();
    doc.insert(
        "package".into(),
        Value::Array(
            packages
                .into_iter()
                .map(|(_, _, _, e)| Value::Table(e))
                .collect(),
        ),
    );
    if !metadata.is_empty() {
        doc.insert("metadata".into(), Value::Table(metadata));
    }
    (doc, notes)
}

fn multi_version_in_inputs(name: &str, inputs: [&Lock; 3]) -> bool {
    let prefix = format!("{name}@");
    inputs.iter().any(|lock| {
        lock.packages
            .keys()
            .filter(|k| k.starts_with(&prefix))
            .count()
            > 1
    })
}

/// Per-key 3-way merge of `[metadata]`. content-hash is special: it is a
/// hash poetry computes from pyproject.toml, so when both sides changed it
/// neither value is right — take theirs and warn instead of blocking.
fn merge_metadata(base: &Lock, ours: &Lock, theirs: &Lock, notes: &mut Vec<String>) -> Table {
    let mut keys: Vec<&String> = base
        .metadata
        .keys()
        .chain(ours.metadata.keys())
        .chain(theirs.metadata.keys())
        .collect();
    keys.sort();
    keys.dedup();
    let mut out = Table::new();
    for key in keys {
        let (b, o, t) = (
            base.metadata.get(key),
            ours.metadata.get(key),
            theirs.metadata.get(key),
        );
        let winner = if o == t {
            o
        } else if o == b {
            t
        } else if t == b {
            o
        } else {
            if key == "content-hash" {
                notes.push(
                    "metadata.content-hash differs on both sides and cannot be recomputed \
                     offline; taking theirs — run `poetry lock --no-update` to refresh it"
                        .to_string(),
                );
            } else {
                notes.push(format!(
                    "metadata.{key} differs on both sides, taking theirs"
                ));
            }
            t
        };
        if let Some(value) = winner {
            out.insert(key.clone(), value.clone());
        }
    }
    out
}

/// Numeric version components; pre-release/build metadata is dropped for
/// comparison (a released version always beats its own pre-releases here,
/// which is the right bias for a lockfile).
fn parse_version(version: &str) -> Vec<u64> {
    version
        .split(['-', '+'])
        .next()
        .unwrap_or("")
        .split('.')
        .map(|part| part.parse().unwrap_or(0))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::{merge3, parse, Lock};
    use toml::Value;

    fn lock(text: &str) -> Lock {
        parse(text).unwrap()
    }

    fn pkg(name: &str, version: &str) -> String {
        format!(
            "[[package]]\nname = \"{name}\"\nversion = \"{version}\"\noptional = false\n\
             files = [{{file = \"{name}-{version}.whl\", hash = \"sha256:{name}\"}}]\n"
        )
    }

    fn names_and_versions(doc: &toml::Table) -> Vec<(String, String)> {
        match doc.get("package") {
            Some(Value::Array(pkgs)) => pkgs
                .iter()
                .map(|p| {
                    (
                        p["name"].as_str().unwrap().to_string(),
                        p["version"].as_str().unwrap().to_string(),
                    )
                })
                .collect(),
            _ => Vec::new(),
        }
    }

    #[test]
    fn disjoint_additions_merge_clean() {
        let base = lock(&pkg("attrs", "23.1.0"));
        let ours = lock(&format!("{}{}", pkg("attrs", "23.1.0"), pkg("idna", "3.6")));
        let theirs = lock(&format!(
            "{}{}",
            pkg("attrs", "23.1.0"),
            pkg("yarl", "1.9.4")
        ));
        let (doc, notes) = merge3(&base, &ours, &theirs);
        assert!(notes.is_empty());
        assert_eq!(
            names_and_versions(&doc),
            [
                ("attrs".into(), "23.1.0".into()),
                ("idna".into(), "3.6".into()),
                ("yarl".into(), "1.9.4".into())
            ]
        );
    }

    #[test]
    fn concurrent_bump_takes_higher_version() {
        let base = lock(&pkg("attrs", "23.1.0"));
        let ours = lock(&pkg("attrs", "23.2.0"));
        let theirs = lock(&pkg("attrs", "23.10.0"));
        let (doc, notes) = merge3(&base, &ours, &theirs);
        assert_eq!(
            names_and_versions(&doc),
            [("attrs".into(), "23.10.0".into())]
        );
        assert!(notes
            .iter()
            .any(|n| n.contains("keeping 23.10.0 over 23.2.0")));
    }

    #[test]
    fn deletion_vs_modification_keeps_modified_entry() {
        let base = lock(&pkg("attrs", "23.1.0"));
        let ours = lock("");
        let mut modified = lock(&pkg("attrs", "23.1.0"));
        modified
            .packages
            .get_mut("attrs@23.1.0")
            .unwrap()
            .insert("description".into(), Value::String("kept".into()));
        let (doc, notes) = merge3(&base, &ours, &modified);
        assert_eq!(
            names_and_versions(&doc),
            [("attrs".into(), "23.1.0".into())]
        );
        assert!(notes.iter().any(|n| n.contains("deleted vs modified")));
    }

    #[test]
    fn plain_deletion_is_taken() {
        let base = lock(&format!("{}{}", pkg("attrs", "23.1.0"), pkg("idna", "3.6")));
        let ours = lock(&pkg("attrs", "23.1.0"));
        let theirs = base.clone();
        let (doc, notes) = merge3(&base, &ours, &theirs);
        assert!(notes.is_empty());
        assert_eq!(
            names_and_versions(&doc),
            [("attrs".into(), "23.1.0".into())]
        );
    }

    #[test]
    fn marker_duplicates_on_one_side_are_preserved() {
        let two = format!("{}{}", pkg("urllib3", "1.26.18"), pkg("urllib3", "2.2.1"));
        let base = lock(&two);
        let ours = lock(&two);
        let theirs = lock(&format!("{two}{}", pkg("idna", "3.6")));
        let (doc, notes) = merge3(&base, &ours, &theirs);
        assert!(notes.is_empty());
        assert_eq!(names_and_versions(&doc).len(), 3);
    }

    #[test]
    fn content_hash_both_changed_takes_theirs_and_warns() {
        let meta = |hash: &str| {
            format!(
                "{}[metadata]\nlock-version = \"2.0\"\npython-versions = \"^3.10\"\ncontent-hash = \"{hash}\"\n",
                pkg("attrs", "23.1.0")
            )
        };
        let base = lock(&meta("aaa"));
        let ours = lock(&meta("bbb"));
        let theirs = lock(&meta("ccc"));
        let (doc, notes) = merge3(&base, &ours, &theirs);
        assert_eq!(doc["metadata"]["content-hash"].as_str(), Some("ccc"));
        assert!(notes.iter().any(|n| n.contains("poetry lock --no-update")));
    }

    #[test]
    fn render_puts_packages_before_metadata() {
        let text = format!(
            "{}[metadata]\nlock-version = \"2.0\"\ncontent-hash = \"aaa\"\n",
            pkg("attrs", "23.1.0")
        );
        let one = lock(&text);
        let (doc, _) = merge3(&one, &one.clone(), &one.clone());
        let out = super::render(doc);
        assert!(out.starts_with("# This file is automatically @generated by Poetry"));
        assert!(out.find("[[package]]").unwrap() < out.find("[metadata]").unwrap());
        // The merged file must still parse as the same lock.
        let reparsed = parse(&out).unwrap();
        assert_eq!(
            reparsed.packages.keys().collect::<Vec<_>>(),
            ["attrs@23.1.0"]
        );
        assert_eq!(reparsed.metadata["content-hash"].as_str(), Some("aaa"));
    }
}
