//! Structural 3-way merge for yarn.lock v1.
//!
//! yarn's v1 lockfile is a custom YAML-looking-but-not-YAML format: blocks
//! separated by blank lines, each keyed by an unindented comma-separated
//! descriptor line ending in `:`. Two branches each adding a dependency
//! produce adjacent blocks, which git's line merge flags as a conflict —
//! structurally they are disjoint entries in a map keyed by the descriptor
//! line, so treat each block as an atomic value and 3-way merge the map.
//! Concurrent bumps of the same descriptor resolve to the higher version;
//! yarn normalizes the rest on the next install.
//!
//! Invoked by the gitwasm host as: yarn-lock-merge <base> <ours> <theirs> <result> [path]

use std::collections::BTreeMap;
use std::process::exit;

const HEADER: &str =
    "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n";

/// Blocks keyed by their full descriptor line; the value is the indented
/// body verbatim.
type Lock = BTreeMap<String, Vec<String>>;

fn main() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() < 5 {
        eprintln!("usage: yarn-lock-merge <base> <ours> <theirs> <result> [path]");
        exit(2);
    }
    let base = read_lock(&args[1]);
    let ours = read_lock(&args[2]);
    let theirs = read_lock(&args[3]);

    match merge3(&base, &ours, &theirs) {
        Ok((merged, notes)) => {
            for note in notes {
                eprintln!("yarn-lock-merge: {note}");
            }
            std::fs::write(&args[4], serialize(&merged)).expect("write result");
            eprintln!("yarn-lock-merge: clean structural merge");
        }
        Err(key) => {
            eprintln!("yarn-lock-merge: real conflict at {key}");
            exit(1);
        }
    }
}

fn read_lock(path: &str) -> Lock {
    let text = std::fs::read_to_string(path).unwrap_or_default();
    if text.trim().is_empty() {
        return Lock::new(); // absent side (e.g. empty base when there is no common ancestor)
    }
    // Refuse yarn berry (v2+) lockfiles: they are real YAML with different
    // semantics; falling through would silently rewrite them as v1.
    if !text.lines().any(|l| l.trim() == "# yarn lockfile v1") {
        eprintln!("yarn-lock-merge: {path} is not a yarn v1 lockfile — refusing");
        exit(1);
    }
    match parse(&text) {
        Ok(lock) => lock,
        Err(line) => {
            eprintln!("yarn-lock-merge: {path}: unrecognized line {line:?} — refusing");
            exit(1);
        }
    }
}

/// Parse blocks: an unindented line ending in `:` opens a block, indented
/// lines are its body, a blank line closes it. Comments only appear at top
/// level (yarn never writes them inside a body).
fn parse(text: &str) -> Result<Lock, String> {
    let mut blocks = Lock::new();
    let mut current: Option<(String, Vec<String>)> = None;
    for line in text.lines() {
        if line.trim().is_empty() {
            if let Some((key, body)) = current.take() {
                blocks.insert(key, body);
            }
        } else if line.starts_with(' ') || line.starts_with('\t') {
            match current.as_mut() {
                Some((_, body)) => body.push(line.to_string()),
                None => return Err(line.to_string()), // indented line outside any block
            }
        } else if line.starts_with('#') {
            continue;
        } else if line.ends_with(':') {
            if let Some((key, body)) = current.take() {
                blocks.insert(key, body);
            }
            current = Some((line.to_string(), Vec::new()));
        } else {
            return Err(line.to_string());
        }
    }
    if let Some((key, body)) = current.take() {
        blocks.insert(key, body);
    }
    Ok(blocks)
}

/// Canonical output: header (yarn writes two blank lines after it), blocks
/// in lexicographic key order, one blank line between blocks.
fn serialize(blocks: &Lock) -> String {
    let mut out = format!("{HEADER}\n");
    for (key, body) in blocks {
        out.push('\n');
        out.push_str(key);
        out.push('\n');
        for line in body {
            out.push_str(line);
            out.push('\n');
        }
    }
    out
}

/// Classic 3-way merge of the block maps. Blocks changed on both sides
/// resolve to the higher `version` when both have one; anything else
/// (including deletion-vs-modification) is a genuine conflict.
fn merge3(base: &Lock, ours: &Lock, theirs: &Lock) -> Result<(Lock, Vec<String>), String> {
    let mut keys: Vec<&String> = base
        .keys()
        .chain(ours.keys())
        .chain(theirs.keys())
        .collect();
    keys.sort();
    keys.dedup();

    let mut merged = Lock::new();
    let mut notes = Vec::new();
    for key in keys {
        let (b, o, t) = (base.get(key), ours.get(key), theirs.get(key));
        let winner = if o == t {
            o
        } else if o == b {
            t
        } else if t == b {
            o
        } else {
            match (o.and_then(|b| version_of(b)), t.and_then(|b| version_of(b))) {
                (Some(ov), Some(tv)) if parse_version(ov) != parse_version(tv) => {
                    let (winner, loser) = if parse_version(ov) > parse_version(tv) {
                        (o, tv)
                    } else {
                        (t, ov)
                    };
                    let kept = version_of(winner.unwrap()).unwrap();
                    notes.push(format!(
                        "{key} both branches bumped, keeping {kept} over {loser}"
                    ));
                    winner
                }
                _ => return Err(key.clone()),
            }
        };
        if let Some(body) = winner {
            merged.insert(key.clone(), body.clone());
        }
    }
    Ok((merged, notes))
}

/// The value of the block's `version "x.y.z"` line, if present.
fn version_of(body: &[String]) -> Option<&str> {
    body.iter()
        .find_map(|line| line.trim().strip_prefix("version \""))
        .and_then(|rest| rest.strip_suffix('"'))
}

/// Numeric version components; pre-release/build metadata is dropped for
/// comparison (a released version always beats its own pre-releases here,
/// which is the right bias for a lockfile).
fn parse_version(version: &str) -> Vec<u64> {
    version
        .split(['-', '+'])
        .next()
        .unwrap_or("")
        .split('.')
        .map(|part| part.parse().unwrap_or(0))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::{merge3, parse, serialize, Lock};

    fn lock(blocks: &[(&str, &[&str])]) -> Lock {
        blocks
            .iter()
            .map(|(key, body)| {
                (
                    key.to_string(),
                    body.iter().map(|line| line.to_string()).collect(),
                )
            })
            .collect()
    }

    const LODASH: (&str, &[&str]) = (
        "lodash@^4.17.15:",
        &[
            "  version \"4.17.15\"",
            "  resolved \"https://registry.yarnpkg.com/lodash/-/lodash-4.17.15.tgz#b447f6d\"",
            "  integrity sha512-8xOcR",
        ],
    );

    #[test]
    fn disjoint_additions_merge_clean() {
        let base = lock(&[LODASH]);
        let left = ("left-pad@^1.3.0:", &["  version \"1.3.0\""][..]);
        let right = ("right-pad@^1.0.1:", &["  version \"1.0.1\""][..]);
        let ours = lock(&[LODASH, left]);
        let theirs = lock(&[LODASH, right]);
        let (merged, notes) = merge3(&base, &ours, &theirs).unwrap();
        assert!(notes.is_empty());
        assert_eq!(merged.len(), 3);
        assert!(merged.contains_key("left-pad@^1.3.0:"));
        assert!(merged.contains_key("right-pad@^1.0.1:"));
    }

    #[test]
    fn concurrent_bump_takes_higher_version() {
        let base = lock(&[("lodash@^4.17.0:", &["  version \"4.17.2\""][..])]);
        let ours = lock(&[("lodash@^4.17.0:", &["  version \"4.17.21\""][..])]);
        let theirs = lock(&[("lodash@^4.17.0:", &["  version \"4.17.3\""][..])]);
        let (merged, notes) = merge3(&base, &ours, &theirs).unwrap();
        assert_eq!(merged["lodash@^4.17.0:"], vec!["  version \"4.17.21\""]);
        assert_eq!(notes.len(), 1);
        assert!(notes[0].contains("keeping 4.17.21 over 4.17.3"));
    }

    #[test]
    fn deletion_vs_modification_conflicts() {
        let base = lock(&[("lodash@^4.17.0:", &["  version \"4.17.2\""][..])]);
        let ours = lock(&[]);
        let theirs = lock(&[("lodash@^4.17.0:", &["  version \"4.17.3\""][..])]);
        assert_eq!(
            merge3(&base, &ours, &theirs).unwrap_err(),
            "lodash@^4.17.0:"
        );
    }

    #[test]
    fn deletion_on_one_side_only_is_taken() {
        let base = lock(&[LODASH, ("left-pad@^1.3.0:", &["  version \"1.3.0\""][..])]);
        let ours = lock(&[LODASH]);
        let theirs = base.clone();
        let (merged, notes) = merge3(&base, &ours, &theirs).unwrap();
        assert!(notes.is_empty());
        assert_eq!(merged, lock(&[LODASH]));
    }

    #[test]
    fn same_version_different_body_conflicts() {
        let base = lock(&[("a@^1.0.0:", &["  version \"1.0.0\""][..])]);
        let ours = lock(&[(
            "a@^1.0.0:",
            &["  version \"1.0.1\"", "  integrity sha512-one"][..],
        )]);
        let theirs = lock(&[(
            "a@^1.0.0:",
            &["  version \"1.0.1\"", "  integrity sha512-two"][..],
        )]);
        assert!(merge3(&base, &ours, &theirs).is_err());
    }

    #[test]
    fn round_trip_parse_serialize() {
        let fixture = "\
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


\"@babel/code-frame@^7.0.0\", \"@babel/code-frame@^7.5.5\":
  version \"7.5.5\"
  resolved \"https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.5.5.tgz#bc0782f\"
  integrity sha512-27d4lZ
  dependencies:
    \"@babel/highlight\" \"^7.0.0\"

left-pad@^1.3.0:
  version \"1.3.0\"
  resolved \"https://registry.yarnpkg.com/left-pad/-/left-pad-1.3.0.tgz#5b8a3a7\"
  integrity sha512-XI5MP

lodash@^4.17.13, lodash@^4.17.15:
  version \"4.17.15\"
  resolved \"https://registry.yarnpkg.com/lodash/-/lodash-4.17.15.tgz#b447f6d\"
  integrity sha512-8xOcR
";
        let parsed = parse(fixture).unwrap();
        assert_eq!(parsed.len(), 3);
        assert_eq!(serialize(&parsed), fixture);
    }
}
