# gitwasm end-to-end demo (Windows). See run-demo.sh for the CI/unix version.
# Proves four things in a throwaway repo:
#   1. package-lock.json merges that always conflict in git merge cleanly
#   2. Cargo.lock concurrent dependency bumps resolve to the higher version
#   3. a staged AWS key blocks the commit (sandboxed pre-commit)
#   4. commit-lint (opt-in) rejects non-conventional messages

$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent

function Step($msg) { Write-Host "`n=== $msg ===" -ForegroundColor Cyan }
function Assert($cond, $msg) { if (-not $cond) { throw "DEMO FAILED: $msg" }; Write-Host $msg -ForegroundColor Green }

Step "Building gitwasm (stock modules are compiled and embedded automatically)"
cargo build --release -p gitwasm --manifest-path "$root\Cargo.toml"
if ($LASTEXITCODE -ne 0) { throw "build failed" }
$env:PATH = "$root\target\release;$env:PATH"

Step "Creating playground repo"
$play = Join-Path $PSScriptRoot "playground"
if (Test-Path $play) { Remove-Item -Recurse -Force $play }
New-Item -ItemType Directory -Force $play | Out-Null
Push-Location $play
try {
    git init -b main -q
    git config user.email "demo@gitwasm.dev"
    git config user.name "gitwasm demo"

    Set-Content package-lock.json @'
{
  "name": "demo-app",
  "version": "1.0.0",
  "lockfileVersion": 3,
  "packages": {
    "": { "name": "demo-app", "dependencies": { "express": "^4.19.0" } },
    "node_modules/express": { "version": "4.19.2", "resolved": "https://registry.npmjs.org/express/-/express-4.19.2.tgz" }
  }
}
'@

    Set-Content Cargo.lock @'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "demo-app"
version = "0.1.0"
dependencies = ["serde"]

[[package]]
name = "serde"
version = "1.0.100"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "aaa"
'@

    Step "gitwasm init - one command from zero to protected repo"
    gitwasm init
    if ($LASTEXITCODE -ne 0) { throw "gitwasm init failed" }
    git add -A
    git commit -q -m "chore: adopt gitwasm"
    if ($LASTEXITCODE -ne 0) { throw "initial commit failed" }
    gitwasm list

    Step "Scenario 1: npm lockfile - both branches add a dependency (adjacent lines)"
    git checkout -q -b feature
    (Get-Content package-lock.json -Raw) `
        -replace '"express": "\^4\.19\.0"', '"express": "^4.19.0", "left-pad": "^1.3.0"' `
        -replace '"node_modules/express":', ('"node_modules/left-pad": { "version": "1.3.0" },' + "`n    " + '"node_modules/express":') `
        | Set-Content package-lock.json
    git commit -q -am "feat: add left-pad"
    git checkout -q main
    (Get-Content package-lock.json -Raw) `
        -replace '"express": "\^4\.19\.0"', '"express": "^4.19.0", "right-pad": "^1.0.1"' `
        -replace '"node_modules/express":', ('"node_modules/right-pad": { "version": "1.0.1" },' + "`n    " + '"node_modules/express":') `
        | Set-Content package-lock.json
    git commit -q -am "feat: add right-pad"
    git merge feature -m "Merge branch 'feature'"
    if ($LASTEXITCODE -ne 0) { throw "npm lockfile merge conflicted" }
    $merged = Get-Content package-lock.json -Raw
    Assert ($merged -match "left-pad" -and $merged -match "right-pad") "1. npm lockfile merged clean with both dependencies"

    Step "Scenario 2: Cargo.lock - both branches bump serde to different versions"
    git checkout -q -b cargo-feature
    (Get-Content Cargo.lock -Raw) -replace '1\.0\.100', '1.0.150' -replace 'checksum = "aaa"', 'checksum = "ccc"' | Set-Content Cargo.lock
    git commit -q -am "chore: bump serde to 1.0.150"
    git checkout -q main
    (Get-Content Cargo.lock -Raw) -replace '1\.0\.100', '1.0.120' -replace 'checksum = "aaa"', 'checksum = "bbb"' | Set-Content Cargo.lock
    git commit -q -am "chore: bump serde to 1.0.120"
    git merge cargo-feature -m "Merge branch 'cargo-feature'"
    if ($LASTEXITCODE -ne 0) { throw "Cargo.lock merge conflicted" }
    $lock = Get-Content Cargo.lock -Raw
    Assert ($lock -match '1\.0\.150' -and $lock -notmatch '1\.0\.120') "2. Cargo.lock merged clean, higher version (1.0.150) won"

    Step "Scenario 3: staged AWS key must block the commit"
    # Assembled at runtime so this script itself never contains a key-shaped literal.
    Set-Content config.js ('const awsKey = "' + 'AKIA' + 'IOSFODNN7EXAMPLE' + '";')
    git add config.js
    git commit -q -m "feat: add config" 2>&1 | Out-String | Write-Host
    Assert ($LASTEXITCODE -ne 0) "3. commit with AWS key was blocked by sandboxed pre-commit"
    Set-Content config.js 'const awsKey = process.env.AWS_ACCESS_KEY_ID;'
    git add config.js
    git commit -q -m "feat: add config (key from env)"
    if ($LASTEXITCODE -ne 0) { throw "clean commit was blocked" }

    Step "Scenario 4: enable opt-in commit-lint, reject a sloppy message"
    (Get-Content .gitwasm\manifest.toml -Raw) -replace '# commit-msg', 'commit-msg' | Set-Content .gitwasm\manifest.toml
    gitwasm install | Out-Null
    git commit -q --allow-empty -m "asdf" 2>&1 | Out-String | Write-Host
    Assert ($LASTEXITCODE -ne 0) "4a. non-conventional message rejected"
    git commit -q --allow-empty -m "feat: a proper conventional message"
    Assert ($LASTEXITCODE -eq 0) "4b. conventional message accepted"

    Step "Scenario 5: sign .gitwasm/, then tamper with a module - must refuse to run"
    $env:GITWASM_KEY_PATH = Join-Path $PSScriptRoot "demo-signing-key"
    if (Test-Path $env:GITWASM_KEY_PATH) { Remove-Item $env:GITWASM_KEY_PATH }
    gitwasm keygen | Out-Null
    gitwasm sign
    if ($LASTEXITCODE -ne 0) { throw "gitwasm sign failed" }
    git add .gitwasm; git commit -q -m "chore: sign gitwasm modules"
    if ($LASTEXITCODE -ne 0) { throw "signed commit failed" }
    Add-Content -Path .gitwasm\secret-scan.wasm -Value "x" -NoNewline   # the attack: swap/patch a committed module
    gitwasm verify 2>&1 | Out-String | Write-Host
    Assert ($LASTEXITCODE -ne 0) "5a. tampered module fails gitwasm verify"
    git commit -q --allow-empty -m "feat: innocent looking commit" 2>&1 | Out-String | Write-Host
    Assert ($LASTEXITCODE -ne 0) "5b. tampered module refuses to run - commit blocked fail-closed"
    git checkout -q -- .gitwasm
    git commit -q --allow-empty -m "feat: after restore everything works"
    Assert ($LASTEXITCODE -eq 0) "5c. restored content verifies and runs again"

    Step "Demo complete - all five scenarios passed"
    Write-Host "Every behavior above is a wasm blob COMMITTED IN THE REPO, running sandboxed"
    Write-Host "(one mounted directory, no network, no env, fuel + memory limits)."
    Write-Host "Anyone who clones and runs 'gitwasm install' gets identical behavior on any OS."
}
finally {
    Pop-Location
}
