#!/usr/bin/env bash
# gitwasm end-to-end demo (unix / CI). Mirrors run-demo.ps1.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
step() { printf '\n=== %s ===\n' "$1"; }
ok() { printf '\033[32m%s\033[0m\n' "$1"; }

step "Building gitwasm (stock modules are compiled and embedded automatically)"
cargo build --release -p gitwasm --manifest-path "$ROOT/Cargo.toml"
export PATH="$ROOT/target/release:$PATH"

step "Creating playground repo"
PLAY="$ROOT/demo/playground"
rm -rf "$PLAY"
mkdir -p "$PLAY"
cd "$PLAY"
git init -b main -q
git config user.email demo@gitwasm.dev
git config user.name "gitwasm demo"

cat > package-lock.json <<'EOF'
{
  "name": "demo-app",
  "version": "1.0.0",
  "lockfileVersion": 3,
  "packages": {
    "": { "name": "demo-app", "dependencies": { "express": "^4.19.0" } },
    "node_modules/express": { "version": "4.19.2", "resolved": "https://registry.npmjs.org/express/-/express-4.19.2.tgz" }
  }
}
EOF

cat > Cargo.lock <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "demo-app"
version = "0.1.0"
dependencies = ["serde"]

[[package]]
name = "serde"
version = "1.0.100"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "aaa"
EOF

step "gitwasm init lockfiles - one command from zero to lockfile conflict protection"
gitwasm init lockfiles
git add -A
git commit -q -m "chore: adopt gitwasm"

step "Enable the default hook pack for policy scenarios"
cp "$ROOT/.gitwasm/secret-scan.wasm" "$ROOT/.gitwasm/commit-lint.wasm" .gitwasm/
python3 - <<'PY'
from pathlib import Path

path = Path(".gitwasm/manifest.toml")
lines = path.read_text().splitlines()

if 'pre-commit = "secret-scan.wasm"' not in lines:
    hooks = lines.index("[hooks]")
    lines.insert(hooks + 1, 'pre-commit = "secret-scan.wasm"')

if '# commit-msg = "commit-lint.wasm"' not in lines and 'commit-msg = "commit-lint.wasm"' not in lines:
    pre_commit = lines.index('pre-commit = "secret-scan.wasm"')
    lines.insert(pre_commit + 1, '# commit-msg = "commit-lint.wasm"')

path.write_text("\n".join(lines) + "\n")
PY
gitwasm install
git add -A
git commit -q -m "chore: enable gitwasm hooks"
gitwasm list

step "Scenario 1: npm lockfile - both branches add a dependency (adjacent lines)"
git checkout -q -b feature
sed -i.bak -e 's|"express": "\^4.19.0"|"express": "^4.19.0", "left-pad": "^1.3.0"|' \
    -e 's|"node_modules/express":|"node_modules/left-pad": { "version": "1.3.0" }, "node_modules/express":|' package-lock.json
rm package-lock.json.bak
git commit -q -am "feat: add left-pad"
git checkout -q main
sed -i.bak -e 's|"express": "\^4.19.0"|"express": "^4.19.0", "right-pad": "^1.0.1"|' \
    -e 's|"node_modules/express":|"node_modules/right-pad": { "version": "1.0.1" }, "node_modules/express":|' package-lock.json
rm package-lock.json.bak
git commit -q -am "feat: add right-pad"
git merge feature -m "Merge branch 'feature'"
grep -q left-pad package-lock.json && grep -q right-pad package-lock.json
ok "1. npm lockfile merged clean with both dependencies"

step "Scenario 2: Cargo.lock - both branches bump serde to different versions"
git checkout -q -b cargo-feature
sed -i.bak -e 's/1\.0\.100/1.0.150/' -e 's/checksum = "aaa"/checksum = "ccc"/' Cargo.lock && rm Cargo.lock.bak
git commit -q -am "chore: bump serde to 1.0.150"
git checkout -q main
sed -i.bak -e 's/1\.0\.100/1.0.120/' -e 's/checksum = "aaa"/checksum = "bbb"/' Cargo.lock && rm Cargo.lock.bak
git commit -q -am "chore: bump serde to 1.0.120"
git merge cargo-feature -m "Merge branch 'cargo-feature'"
grep -q '1\.0\.150' Cargo.lock && ! grep -q '1\.0\.120' Cargo.lock
ok "2. Cargo.lock merged clean, higher version (1.0.150) won"

step "Scenario 3: pnpm-lock.yaml - both branches add a dependency"
cat > pnpm-lock.yaml <<'EOF'
lockfileVersion: '9.0'

importers:
  .:
    dependencies:
      express:
        specifier: ^4.19.0
        version: 4.19.2

packages:
  express@4.19.2:
    resolution: {integrity: sha512-express}

snapshots:
  express@4.19.2: {}
EOF
git add pnpm-lock.yaml && git commit -q -m "chore: add pnpm lock baseline"
git checkout -q -b pnpm-feature
python3 - <<'PY'
from pathlib import Path
p = Path("pnpm-lock.yaml")
s = p.read_text()
s = s.replace("      express:\n        specifier: ^4.19.0\n        version: 4.19.2\n", "      express:\n        specifier: ^4.19.0\n        version: 4.19.2\n      left-pad:\n        specifier: ^1.3.0\n        version: 1.3.0\n")
s = s.replace("  express@4.19.2:\n    resolution: {integrity: sha512-express}\n", "  express@4.19.2:\n    resolution: {integrity: sha512-express}\n  left-pad@1.3.0:\n    resolution: {integrity: sha512-left}\n")
s = s.replace("  express@4.19.2: {}\n", "  express@4.19.2: {}\n  left-pad@1.3.0: {}\n")
p.write_text(s)
PY
git commit -q -am "feat: add left-pad to pnpm lock"
git checkout -q main
python3 - <<'PY'
from pathlib import Path
p = Path("pnpm-lock.yaml")
s = p.read_text()
s = s.replace("      express:\n        specifier: ^4.19.0\n        version: 4.19.2\n", "      express:\n        specifier: ^4.19.0\n        version: 4.19.2\n      right-pad:\n        specifier: ^1.0.1\n        version: 1.0.1\n")
s = s.replace("  express@4.19.2:\n    resolution: {integrity: sha512-express}\n", "  express@4.19.2:\n    resolution: {integrity: sha512-express}\n  right-pad@1.0.1:\n    resolution: {integrity: sha512-right}\n")
s = s.replace("  express@4.19.2: {}\n", "  express@4.19.2: {}\n  right-pad@1.0.1: {}\n")
p.write_text(s)
PY
git commit -q -am "feat: add right-pad to pnpm lock"
git merge pnpm-feature -m "Merge branch 'pnpm-feature'"
grep -q '^      left-pad:$' pnpm-lock.yaml && grep -q '^      right-pad:$' pnpm-lock.yaml
grep -q '^  left-pad@1\.3\.0:$' pnpm-lock.yaml && grep -q '^  right-pad@1\.0\.1:$' pnpm-lock.yaml
grep -q '^  left-pad@1\.3\.0: {}$' pnpm-lock.yaml && grep -q '^  right-pad@1\.0\.1: {}$' pnpm-lock.yaml
ok "3. pnpm-lock.yaml merged clean with both dependencies"

step "Scenario 4: go.sum merges via a typed WASI 0.2 component (imports nothing)"
printf 'golang.org/x/sys v0.1.0 h1:base=\ngolang.org/x/sys v0.1.0/go.mod h1:base=\n' > go.sum
git add go.sum && git commit -q -m "chore: add go.sum baseline"
git checkout -q -b gosum-feature
printf 'golang.org/x/text v0.3.0 h1:txt=\ngolang.org/x/text v0.3.0/go.mod h1:txt=\n' >> go.sum
git commit -q -am "feat: add x/text to go.sum"
git checkout -q main
printf 'golang.org/x/net v0.5.0 h1:net=\ngolang.org/x/net v0.5.0/go.mod h1:net=\n' >> go.sum
git commit -q -am "feat: add x/net to go.sum"
git merge gosum-feature -m "Merge branch 'gosum-feature'"
grep -q 'x/text' go.sum && grep -q 'x/net' go.sum && grep -q 'x/sys' go.sum
ok "4. go.sum merged clean by a component that never sees a filesystem"

step "Scenario 5: staged AWS key must block the commit"
# Assembled at runtime so this script itself never contains a key-shaped literal.
printf 'const awsKey = "%s%s";\n' 'AKIA' 'IOSFODNN7EXAMPLE' > config.js
git add config.js
if git commit -q -m "feat: add config"; then
    echo "DEMO FAILED: commit with AWS key went through" >&2
    exit 1
fi
ok "5. commit with AWS key was blocked by sandboxed pre-commit"
echo 'const awsKey = process.env.AWS_ACCESS_KEY_ID;' > config.js
git add config.js
git commit -q -m "feat: add config (key from env)"

step "Scenario 6: enable opt-in commit-lint, reject a sloppy message"
sed -i.bak 's/# commit-msg/commit-msg/' .gitwasm/manifest.toml && rm .gitwasm/manifest.toml.bak
gitwasm install > /dev/null
if git commit -q --allow-empty -m "asdf"; then
    echo "DEMO FAILED: non-conventional message accepted" >&2
    exit 1
fi
ok "6a. non-conventional message rejected"
git commit -q --allow-empty -m "feat: a proper conventional message"
ok "6b. conventional message accepted"

step "Scenario 7: sign .gitwasm/, then tamper with a module - must refuse to run"
export GITWASM_KEY_PATH="$ROOT/demo/demo-signing-key"
rm -f "$GITWASM_KEY_PATH"
gitwasm keygen > /dev/null
gitwasm sign
git add .gitwasm && git commit -q -m "chore: sign gitwasm modules"
printf 'x' >> .gitwasm/secret-scan.wasm   # the attack: swap/patch a committed module
if gitwasm verify; then
    echo "DEMO FAILED: tampered module passed verify" >&2
    exit 1
fi
ok "7a. tampered module fails gitwasm verify"
if git commit -q --allow-empty -m "feat: innocent looking commit"; then
    echo "DEMO FAILED: tampered module was allowed to run" >&2
    exit 1
fi
ok "7b. tampered module refuses to run - commit blocked fail-closed"
git checkout -q -- .gitwasm
git commit -q --allow-empty -m "feat: after restore everything works"
ok "7c. restored content verifies and runs again"

step "Scenario 8: verdicts - every merge above is a re-derivable, cached fact"
gitwasm verdicts
gitwasm audit                       # re-derive all recorded verdicts from content-addressed inputs
VDIR="$(git rev-parse --absolute-git-dir)/gitwasm/verdicts"
V="$VDIR/$(ls "$VDIR" | head -1)"
sed -i.bak 's/^exit_code = 0/exit_code = 1/' "$V" && rm "$V.bak"   # forge a different outcome
if gitwasm audit; then
    echo "DEMO FAILED: a forged verdict passed audit" >&2
    exit 1
fi
ok "8a. a forged verdict fails re-derivation - you cannot lie about a verdict"
sed -i.bak 's/^exit_code = 1/exit_code = 0/' "$V" && rm "$V.bak"
gitwasm audit > /dev/null
ok "8b. restored verdict re-derives - merges are cached and trustlessly checkable"

step "Demo complete - all eight scenarios passed"
echo "Every behavior above is a wasm blob COMMITTED IN THE REPO, running sandboxed."
