#!/usr/bin/env bash
# gitwasm end-to-end demo (unix / CI). Mirrors run-demo.ps1.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
step() { printf '\n=== %s ===\n' "$1"; }
ok() { printf '\033[32m%s\033[0m\n' "$1"; }

step "Building gitwasm (stock modules are compiled and embedded automatically)"
cargo build --release -p gitwasm --manifest-path "$ROOT/Cargo.toml"
export PATH="$ROOT/target/release:$PATH"

step "Creating playground repo"
PLAY="$ROOT/demo/playground"
rm -rf "$PLAY"
mkdir -p "$PLAY"
cd "$PLAY"
git init -b main -q
git config user.email demo@gitwasm.dev
git config user.name "gitwasm demo"

cat > package-lock.json <<'EOF'
{
  "name": "demo-app",
  "version": "1.0.0",
  "lockfileVersion": 3,
  "packages": {
    "": { "name": "demo-app", "dependencies": { "express": "^4.19.0" } },
    "node_modules/express": { "version": "4.19.2", "resolved": "https://registry.npmjs.org/express/-/express-4.19.2.tgz" }
  }
}
EOF

cat > Cargo.lock <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "demo-app"
version = "0.1.0"
dependencies = ["serde"]

[[package]]
name = "serde"
version = "1.0.100"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "aaa"
EOF

step "gitwasm init - one command from zero to protected repo"
gitwasm init
git add -A
git commit -q -m "chore: adopt gitwasm"
gitwasm list

step "Scenario 1: npm lockfile - both branches add a dependency (adjacent lines)"
git checkout -q -b feature
sed -i.bak -e 's|"express": "\^4.19.0"|"express": "^4.19.0", "left-pad": "^1.3.0"|' \
    -e 's|"node_modules/express":|"node_modules/left-pad": { "version": "1.3.0" }, "node_modules/express":|' package-lock.json
rm package-lock.json.bak
git commit -q -am "feat: add left-pad"
git checkout -q main
sed -i.bak -e 's|"express": "\^4.19.0"|"express": "^4.19.0", "right-pad": "^1.0.1"|' \
    -e 's|"node_modules/express":|"node_modules/right-pad": { "version": "1.0.1" }, "node_modules/express":|' package-lock.json
rm package-lock.json.bak
git commit -q -am "feat: add right-pad"
git merge feature -m "Merge branch 'feature'"
grep -q left-pad package-lock.json && grep -q right-pad package-lock.json
ok "1. npm lockfile merged clean with both dependencies"

step "Scenario 2: Cargo.lock - both branches bump serde to different versions"
git checkout -q -b cargo-feature
sed -i.bak -e 's/1\.0\.100/1.0.150/' -e 's/checksum = "aaa"/checksum = "ccc"/' Cargo.lock && rm Cargo.lock.bak
git commit -q -am "chore: bump serde to 1.0.150"
git checkout -q main
sed -i.bak -e 's/1\.0\.100/1.0.120/' -e 's/checksum = "aaa"/checksum = "bbb"/' Cargo.lock && rm Cargo.lock.bak
git commit -q -am "chore: bump serde to 1.0.120"
git merge cargo-feature -m "Merge branch 'cargo-feature'"
grep -q '1\.0\.150' Cargo.lock && ! grep -q '1\.0\.120' Cargo.lock
ok "2. Cargo.lock merged clean, higher version (1.0.150) won"

step "Scenario 3: staged AWS key must block the commit"
# Assembled at runtime so this script itself never contains a key-shaped literal.
printf 'const awsKey = "%s%s";\n' 'AKIA' 'IOSFODNN7EXAMPLE' > config.js
git add config.js
if git commit -q -m "feat: add config"; then
    echo "DEMO FAILED: commit with AWS key went through" >&2
    exit 1
fi
ok "3. commit with AWS key was blocked by sandboxed pre-commit"
echo 'const awsKey = process.env.AWS_ACCESS_KEY_ID;' > config.js
git add config.js
git commit -q -m "feat: add config (key from env)"

step "Scenario 4: enable opt-in commit-lint, reject a sloppy message"
sed -i.bak 's/# commit-msg/commit-msg/' .gitwasm/manifest.toml && rm .gitwasm/manifest.toml.bak
gitwasm install > /dev/null
if git commit -q --allow-empty -m "asdf"; then
    echo "DEMO FAILED: non-conventional message accepted" >&2
    exit 1
fi
ok "4a. non-conventional message rejected"
git commit -q --allow-empty -m "feat: a proper conventional message"
ok "4b. conventional message accepted"

step "Scenario 5: sign .gitwasm/, then tamper with a module - must refuse to run"
export GITWASM_KEY_PATH="$ROOT/demo/demo-signing-key"
rm -f "$GITWASM_KEY_PATH"
gitwasm keygen > /dev/null
gitwasm sign
git add .gitwasm && git commit -q -m "chore: sign gitwasm modules"
printf 'x' >> .gitwasm/secret-scan.wasm   # the attack: swap/patch a committed module
if gitwasm verify; then
    echo "DEMO FAILED: tampered module passed verify" >&2
    exit 1
fi
ok "5a. tampered module fails gitwasm verify"
if git commit -q --allow-empty -m "feat: innocent looking commit"; then
    echo "DEMO FAILED: tampered module was allowed to run" >&2
    exit 1
fi
ok "5b. tampered module refuses to run - commit blocked fail-closed"
git checkout -q -- .gitwasm
git commit -q --allow-empty -m "feat: after restore everything works"
ok "5c. restored content verifies and runs again"

step "Demo complete - all five scenarios passed"
echo "Every behavior above is a wasm blob COMMITTED IN THE REPO, running sandboxed."
